# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/darksoulsAPP.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 670)
        MainWindow.setMinimumSize(QtCore.QSize(590, 670))
        MainWindow.setMaximumSize(QtCore.QSize(590, 670))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 601, 671))
        self.frame.setMinimumSize(QtCore.QSize(601, 671))
        self.frame.setStyleSheet("background-color: #2C2F33;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.defeatBox = QtWidgets.QCheckBox(self.frame)
        self.defeatBox.setGeometry(QtCore.QRect(120, 400, 121, 20))
        self.defeatBox.setStyleSheet("QCheckBox {\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 16px;\n"
"    color: white;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: #B0B0B0;\n"
"    border: 2px solid #8B7500;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #8B7500;\n"
"    border: 2px solid #FFD700;\n"
"    image: url(:/qt-project.org/styles/commonstyle/images/checkbox_checked.png);\n"
"}\n"
"")
        self.defeatBox.setObjectName("defeatBox")
        self.tipBox = QtWidgets.QCheckBox(self.frame)
        self.tipBox.setGeometry(QtCore.QRect(400, 400, 91, 20))
        self.tipBox.setStyleSheet("QCheckBox {\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 16px;\n"
"    color: white;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: #B0B0B0;\n"
"    border: 2px solid #8B7500;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #8B7500;\n"
"    border: 2px solid #FFD700;\n"
"    image: url(:/qt-project.org/styles/commonstyle/images/checkbox_checked.png);\n"
"}\n"
"")
        self.tipBox.setObjectName("tipBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(12, 572, 637, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.bossList = QtWidgets.QListWidget(self.frame)
        self.bossList.setGeometry(QtCore.QRect(140, 330, 301, 41))
        self.bossList.setStyleSheet("QListWidget {\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 16px;\n"
"    color: white;\n"
"    border: 3px solid #8B7500;\n"
"    border-radius: 5px;\n"
"    background-color: #1E1E1E;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #8B7500;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #A88E45;\n"
"    color: black;\n"
"}\n"
"")
        self.bossList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.bossList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bossList.setResizeMode(QtWidgets.QListView.Adjust)
        self.bossList.setObjectName("bossList")
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.bossList.addItem(item)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 613, 551, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 16px;\n"
"    color: white;\n"
"    border: 3px solid #8B7500;\n"
"    border-radius: 5px;\n"
"    background-color: #1E1E1E;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #8B0000;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 421, 271))
        self.label_2.setMinimumSize(QtCore.QSize(421, 271))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textLore = QtWidgets.QTextEdit(self.frame)
        self.textLore.setGeometry(QtCore.QRect(80, 450, 421, 121))
        self.textLore.setStyleSheet("QTextEdit {\n"
"    background-color: #1E1E1E;\n"
"    color: white;\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 13pt;\n"
"    border: 2px solid #8B7500;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"")
        self.textLore.setReadOnly(True)
        self.textLore.setObjectName("textLore")
        self.playButton = QtWidgets.QPushButton(self.frame)
        self.playButton.setGeometry(QtCore.QRect(510, 30, 51, 41))
        self.playButton.setStyleSheet("QPushButton {\n"
"    background-color: #1E1E1E;\n"
"    color: white;\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 10pt;\n"
"    border: 2px solid #8B7500;\n"
"    border-radius: 5px;\n"
"    padding: 3px 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A88E45;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFD700;\n"
"    color: black;\n"
"}\n"
"")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Sara\PycharmProjects\PythonProject\images\music_note1.jpg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(50, 50))
        self.playButton.setObjectName("playButton")
        self.resetButton = QtWidgets.QPushButton(self.frame)
        self.resetButton.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.resetButton.setStyleSheet("QPushButton {\n"
"    background-color: #111;\n"
"    color: #FFD700;\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 6px;\n"
"    font-family: \"Trajan Pro\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #222;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333;\n"
"}\n"
"")
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.defeatBox.setText(_translate("MainWindow", "Defeated"))
        self.tipBox.setText(_translate("MainWindow", "Tips"))
        self.bossList.setSortingEnabled(True)
        __sortingEnabled = self.bossList.isSortingEnabled()
        self.bossList.setSortingEnabled(False)
        item = self.bossList.item(0)
        item.setText(_translate("MainWindow", "Select a Boss"))
        item = self.bossList.item(1)
        item.setText(_translate("MainWindow", "Iudex Gundyr"))
        item = self.bossList.item(2)
        item.setText(_translate("MainWindow", "Vordt of the Boreal Valley"))
        item = self.bossList.item(3)
        item.setText(_translate("MainWindow", "Curse-rotted Greatwood"))
        item = self.bossList.item(4)
        item.setText(_translate("MainWindow", "Crystal Sage"))
        item = self.bossList.item(5)
        item.setText(_translate("MainWindow", "Abyss Watchers"))
        item = self.bossList.item(6)
        item.setText(_translate("MainWindow", "High Lord Wolnir"))
        item = self.bossList.item(7)
        item.setText(_translate("MainWindow", "Deacons of the Deep"))
        item = self.bossList.item(8)
        item.setText(_translate("MainWindow", "Yhorm the Giant"))
        item = self.bossList.item(9)
        item.setText(_translate("MainWindow", "Aldrich, Devourer of Gods"))
        item = self.bossList.item(10)
        item.setText(_translate("MainWindow", "Dancer of the Boreal Valley"))
        item = self.bossList.item(11)
        item.setText(_translate("MainWindow", "Oceiros, the Consumed King"))
        item = self.bossList.item(12)
        item.setText(_translate("MainWindow", "Champion Gundyr"))
        item = self.bossList.item(13)
        item.setText(_translate("MainWindow", "Lorian, Elder Prince and Lothric, Younger Prince"))
        item = self.bossList.item(14)
        item.setText(_translate("MainWindow", "Nameless King"))
        item = self.bossList.item(15)
        item.setText(_translate("MainWindow", "Soul of Cinder"))
        self.bossList.setSortingEnabled(__sortingEnabled)
        self.resetButton.setText(_translate("MainWindow", "Reset Progress"))
